name: Test action
on:
  workflow_dispatch:
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          dry-run: true
          conflict-label: 'conflicted'
          conflict-requires-labels: 'test-pr'
          conflict-requires-ready-state: 'all'
          update-pr-branches: true
          update-requires-labels: 'test-pr'
          update-requires-ready-state: 'all'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Print Output
        id: output
        run: |
          echo "Updated PRs:"
          echo "${{ steps.test-action.outputs.updated-prs }}"
          echo "Conflicted PRs:"
          echo "${{ steps.test-action.outputs.conflicted-prs }}"
