name: Test updating PR from forks
on:
  workflow_dispatch:
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Generate Sequelize Bot Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: '${{ secrets.SEQUELIZE_BOT_APP_ID }}'
          private-key: '${{ secrets.SEQUELIZE_BOT_PRIVATE_KEY }}'
      - name: Configure git
        run: |
          git config --global user.name "sequelize[bot]"
          git config --global user.email "bot@sequelize.org"
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          update-pr-branches: true
          update-requires-labels: 'test-pr'
          update-requires-source: 'fork'
        env:
          GITHUB_TOKEN: '${{ steps.generate-token.outputs.token }}'
      - name: Print Output
        id: output
        run: |
          echo "Updated PRs:"
          echo "${{ steps.test-action.outputs.updated-prs }}"
          echo "Conflicted PRs:"
          echo "${{ steps.test-action.outputs.conflicted-prs }}"
